// Auto-generated by scripts/syncVersion.js — do not edit manually.
// Committed to git because svelte-package scopes builds to src/lib/,
// so a runtime import of ../../package.json escapes the package boundary.
// See https://svelte.dev/docs/kit/packaging
export const VERSION = '2.2.1'
export const INTEGRATION_INFO_PACKAGE_NAME = 'fingerprintjs-pro-svelte'
