import fs from 'fs'
import path from 'path'
import pkg from '../package.json' with { type: 'json' }

const versionFile = path.resolve('./src/lib/version.ts')

const content = `// Auto-generated by scripts/syncVersion.js — do not edit manually.
// Committed to git because svelte-package scopes builds to src/lib/,
// so a runtime import of ../../package.json escapes the package boundary.
// See https://svelte.dev/docs/kit/packaging
export const VERSION = '${pkg.version}'
export const INTEGRATION_INFO_PACKAGE_NAME = 'fingerprintjs-pro-svelte'
`

fs.writeFileSync(versionFile, content)
